package session

import (
	"crypto/rand"
	"fmt"
	"sync"
	"time"
)

// SessionType identifies what kind of activity initiated the session.
type SessionType string

const (
	TypeChat      SessionType = "chat"
	TypeAgent     SessionType = "agent"
	TypeWorkflow  SessionType = "workflow"
	TypeComposite SessionType = "composite"
)

// SessionState tracks the lifecycle state.
type SessionState string

const (
	StateActive    SessionState = "active"
	StateCompleted SessionState = "completed"
	StateExpired   SessionState = "expired"
)

// Session is the top-level context that unifies chat, agent, and workflow.
// The ID is generated by Cloud and passed to the router.
type Session struct {
	ID     string       `json:"id"`
	Type   SessionType  `json:"type"`
	State  SessionState `json:"state"`
	UserID int64        `json:"user_id"`

	AgentIDs []string `json:"agent_ids,omitempty"`
	RunIDs   []int64  `json:"run_ids,omitempty"`

	Context *Context `json:"context"`

	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	ExpiresAt time.Time `json:"expires_at"`

	mu sync.RWMutex
}

// BindAgent adds an agent session ID to this session.
func (s *Session) BindAgent(agentID string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.AgentIDs = append(s.AgentIDs, agentID)
	s.UpdatedAt = time.Now()
	if s.Type == TypeChat {
		s.Type = TypeComposite
	}
}

// BindRun adds a workflow run ID to this session.
func (s *Session) BindRun(runID int64) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.RunIDs = append(s.RunIDs, runID)
	s.UpdatedAt = time.Now()
	if s.Type == TypeChat {
		s.Type = TypeComposite
	}
}

// Complete marks the session as completed.
func (s *Session) Complete() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.State = StateCompleted
	s.UpdatedAt = time.Now()
}

// IsActive returns true if the session is active and not expired.
func (s *Session) IsActive() bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.State == StateActive && time.Now().Before(s.ExpiresAt)
}

// generateID creates a random hex ID (16 bytes = 32 chars).
func generateID() string {
	b := make([]byte, 16)
	rand.Read(b)
	return fmt.Sprintf("%x", b)
}
