package session

import (
	"encoding/json"
	"log"
	"os"
	"path/filepath"
	"sync"
	"time"
)

const DefaultTTL = 24 * time.Hour

// Store manages active sessions with TTL-based expiry.
// Session IDs are generated by Cloud — the router only registers them locally.
type Store struct {
	mu       sync.RWMutex
	sessions map[string]*Session
	filePath string
	ttl      time.Duration
	stopGC   chan struct{}
}

// NewStore creates a session store. Pass empty dataDir to disable file persistence.
func NewStore(dataDir string, ttl time.Duration) *Store {
	if ttl == 0 {
		ttl = DefaultTTL
	}
	s := &Store{
		sessions: make(map[string]*Session),
		ttl:      ttl,
		stopGC:   make(chan struct{}),
	}
	if dataDir != "" {
		s.filePath = filepath.Join(dataDir, "sessions.json")
		s.load()
	}
	go s.gcLoop()
	return s
}

// Register registers a Cloud-created session locally for context tracking.
func (s *Store) Register(id string, sessionType SessionType, userID int64) *Session {
	s.mu.Lock()
	defer s.mu.Unlock()
	if existing, ok := s.sessions[id]; ok {
		return existing
	}
	now := time.Now()
	sess := &Session{
		ID:        id,
		Type:      sessionType,
		State:     StateActive,
		UserID:    userID,
		Context:   NewContext(),
		CreatedAt: now,
		UpdatedAt: now,
		ExpiresAt: now.Add(s.ttl),
	}
	s.sessions[id] = sess
	return sess
}

// Get returns a session by ID, or nil if not found or expired.
func (s *Store) Get(id string) *Session {
	s.mu.RLock()
	sess, ok := s.sessions[id]
	s.mu.RUnlock()
	if !ok {
		return nil
	}
	if time.Now().After(sess.ExpiresAt) {
		return nil
	}
	return sess
}

// GetOrRegister returns existing session or registers a new one with Cloud-provided ID.
func (s *Store) GetOrRegister(id string, sessionType SessionType, userID int64) *Session {
	if sess := s.Get(id); sess != nil {
		s.Touch(id)
		return sess
	}
	return s.Register(id, sessionType, userID)
}

// Touch extends the session TTL.
func (s *Store) Touch(id string) {
	s.mu.RLock()
	sess, ok := s.sessions[id]
	s.mu.RUnlock()
	if !ok {
		return
	}
	sess.mu.Lock()
	sess.ExpiresAt = time.Now().Add(s.ttl)
	sess.UpdatedAt = time.Now()
	sess.mu.Unlock()
}

// List returns all active (non-expired) sessions.
func (s *Store) List() []*Session {
	s.mu.RLock()
	defer s.mu.RUnlock()
	now := time.Now()
	result := make([]*Session, 0, len(s.sessions))
	for _, sess := range s.sessions {
		if now.Before(sess.ExpiresAt) {
			result = append(result, sess)
		}
	}
	return result
}

// Delete removes a session.
func (s *Store) Delete(id string) {
	s.mu.Lock()
	delete(s.sessions, id)
	s.mu.Unlock()
}

// Count returns the number of sessions (including expired not yet GC'd).
func (s *Store) Count() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.sessions)
}

// Save persists sessions to disk.
func (s *Store) Save() error {
	if s.filePath == "" {
		return nil
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	data, err := json.MarshalIndent(s.sessions, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(s.filePath, data, 0600)
}

// Close stops the GC loop and persists sessions.
func (s *Store) Close() {
	close(s.stopGC)
	s.Save()
}

func (s *Store) load() {
	if s.filePath == "" {
		return
	}
	data, err := os.ReadFile(s.filePath)
	if err != nil {
		return
	}
	var sessions map[string]*Session
	if err := json.Unmarshal(data, &sessions); err != nil {
		log.Printf("session: load error: %v", err)
		return
	}
	// Restore contexts for deserialized sessions
	for _, sess := range sessions {
		if sess.Context == nil {
			sess.Context = NewContext()
		}
	}
	s.sessions = sessions
}

func (s *Store) gcLoop() {
	ticker := time.NewTicker(5 * time.Minute)
	defer ticker.Stop()
	for {
		select {
		case <-s.stopGC:
			return
		case <-ticker.C:
			s.gc()
		}
	}
}

func (s *Store) gc() {
	s.mu.Lock()
	now := time.Now()
	for id, sess := range s.sessions {
		if now.After(sess.ExpiresAt) {
			delete(s.sessions, id)
		}
	}
	s.mu.Unlock()
	s.Save()
}
